apachedir: /etc/apache2
apachelogdir: /var/log/apache2
apachedocroot: /var/www

conf_available: "{{apachedir}}/conf-available"
conf_enabled: "{{apachedir}}/conf-enabled"
mods_available: "{{apachedir}}/mods-available"
mods_enabled: "{{apachedir}}/mods-enabled"
sites_available: "{{apachedir}}/sites-available"
sites_enabled: "{{apachedir}}/sites-enabled"

WEBSERVERNAME: apache2

packages:
- apache2
- libapache2-mod-php
- mysql-client
- php-common
- php7.4-cli
- php7.4-common
- php7.4-curl
- php7.4-fpm
- php7.4-gd
- php7.4-gmp
- php7.4-intl
- php7.4-json
- php7.4-mbstring
- php7.4-mysql
- php7.4-opcache
- php7.4-readline
- php7.4-soap
- php7.4-xml
- php7.4-xmlrpc
- php7.4-zip