- name: Include Vars
  include_vars: "vars-{{ansible_distribution}}-{{ansible_distribution_release}}.yml"

- name: Atualizando repositórios
  yum:
    name: "*"
    state: latest

- name: Install pacotes communs
  yum:
    name: "{{ packages }}"
    state: present