- hosts: all:!local
  become: yes
  pre_tasks:

  - name: "Atualizando os Repos"
    raw: apt update
    when:
    - ansible_distribution == "Ubuntu"

  - name: "Instalando o Python"
    raw: apt install python3 -y
    when:
    - ansible_distribution == "Ubuntu"

  - name: "Atualizando os Repos"
    raw: yum update -y
    when:
    - ansible_distribution == "Amazon"

  - name: "Instalando o Python"
    raw: yum install python3 -y
    when:
    - ansible_distribution == "Amazon"

  roles:
  - { role: default, tags: ["default_role"]}

- hosts: web
  become: yes
  roles:
  - { role: web-server, tags: ["web-server_role"]}
  - { role: wordpress, tags: ["wordpress_role"]}

- hosts: database
  become: yes
  roles:
  - { role: db-server, tags: ["db-server_role"]}  

- hosts: local
  roles:
  - { role: dns, tags: ["dns_role"]}